name: check diff sample

on:
  pull_request:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
      - uses: technote-space/get-diff-action@v5
        id: diff
        with:
          PATTERNS: |
            diff_target/*
        continue-on-error: true
      - name: echo
        run: |
          echo "test"
        if: steps.diff.outputs.diff
