name: check diff sample

permissions:
  contents: 'read'
  id-token: 'write'
  pull-requests: 'write'

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  commit:
    runs-on: ubuntu-latest
    if: ${{ !failure() && github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: diff
        with:
          PATTERNS: |
            diff_target/*
        continue-on-error: true
      - name: echo
        run: |
          echo "test"
        if: steps.diff.outputs.diff
